version: '3.3'

services:
  kanban-app:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    container_name: kanban-app
    working_dir: /var/www/html
    image: kanban
    ports:
      - "80:80"
    command: 'php -S 0.0.0.0:80'
    links:
      - db

  db:
    image: mysql:8.0
    container_name: kanban-db
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=kanban
      - MYSQL_USER=user_kanban
      - MYSQL_PASSWORD=pass_kanban
    ports:
      - "3306:3306"